"""Run SCIP on the fixed scaling instances reported in Table 5.

The coefficients below are the MATLAB seed-3 instances generated by
Table_5_6_generate_instance.m. The script prints SCIP's evaluated feasible
value, upper bound, optimality gap, runtime, and node count. No result
files are created.
"""
# J. Choi, August 4, 2026

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys
import time


SCRIPT_DIR = Path(__file__).resolve().parent
PACKAGE_DIR = SCRIPT_DIR.parent / "python_packages"
sys.path.insert(0, str(PACKAGE_DIR))

import pyscipopt
from pyscipopt import Model, log, quicksum


parser = argparse.ArgumentParser()
parser.add_argument(
    "--case",
    choices=("m2", "m4", "m6", "m8", "m10", "m12", "n2", "n6", "n8", "all"),
    default="all",
    help="Scaling case to solve. The default solves all nine distinct cases.",
)
parser.add_argument(
    "--time-limit",
    type=float,
    default=600.0,
    help="SCIP time limit in seconds for each case (default: 600).",
)
parser.add_argument(
    "--relative-gap",
    type=float,
    default=1.0e-6,
    help="Relative optimality-gap tolerance (default: 1e-6).",
)
args = parser.parse_args()

if args.time_limit <= 0:
    parser.error("--time-limit must be positive")
if args.relative_gap < 0:
    parser.error("--relative-gap must be nonnegative")


epsilon = 0.05

# For n=4, the m-scaling instances use the first m entries of this list.
terms_n4 = [
    (0.11788408630429641, [0.06753518004156604, 0.9373950194967214, -0.3398159026377111, 0.03542215682326694]),
    (-0.01775704690480906, [0.305399245166099, -0.38799174420379423, -0.6055326285160294, -0.6241185330401131]),
    (0.05287647059403938, [-0.7824427735853888, -0.11894550471458354, 0.2910909825300393, -0.5374954072937678]),
    (-0.025469640896979107, [0.21570061378554345, -0.9120716792860599, 0.16769470684392013, -0.3057400568348514]),
    (0.01339470540955342, [-0.39694145076077675, 0.4986318929835195, -0.10403927871466037, -0.7635309741275301]),
    (0.13091509495812911, [0.6352372718228958, -0.22040916849709005, -0.7054076874644711, -0.22426190357582515]),
    (-0.03660178760133326, [0.3764090022412205, 0.19339257849663036, 0.7984741281316332, 0.42819929976428217]),
    (-0.08248364854805042, [-0.8504722768659321, 0.48971510698634146, 0.16908600464313725, -0.09102715696787783]),
    (-0.012694080203106617, [-0.31989917887551905, -0.13028155351743348, -0.8310243572867941, -0.43599283223915924]),
    (-0.013613377343415967, [0.7447005686040395, 0.23075720606443453, -0.5325534435541113, -0.32948293541367846]),
    (-0.004924340294524043, [-0.598747200480686, -0.19108362906392748, 0.03172964198486058, -0.7771628313550598]),
    (0.05675412412647424, [-0.2693489410266761, 0.4898531183185869, 0.5443730522017539, 0.6254222977140416]),
]

terms_n2 = [
    (-0.0627285783261167, [0.07185933899031215, 0.9974147760083943]),
    (0.11888792668003141, [0.03201400585948675, 0.9994874203454633]),
    (-0.13455983900975102, [-0.5394983706521958, -0.841986643637312]),
    (-0.012950032681586676, [-0.26195476531868217, -0.9650801525919152]),
]

terms_n6 = [
    (-0.11232440686084912, [0.04429363079776369, 0.6148000031938239, -0.2228716962238006, 0.023231979768538562, 0.7253097794224889, 0.20922054477533128]),
    (-0.0664538152056074, [-0.4922078625760715, -0.5073154354945802, -0.17275804573608278, -0.6364662270511834, -0.09675441983250419, 0.2367835522725259]),
    (-0.06494247546860438, [0.2397389316692495, 0.20771551905016186, -0.8783073860986574, 0.16148675918317737, -0.2944217611870953, -0.12326190190142255]),
    (-0.08341263482034557, [0.36557728819282637, -0.07627750633933131, -0.5597908735893778, 0.10191557254213872, 0.6921730381191639, -0.24016425130432778]),
]

terms_n8 = [
    (-0.13455983900975102, [0.039733015351829, 0.5514982069710583, -0.19992410574740085, 0.020839940013301597, 0.6506295393169815, 0.1876785209916901, -0.2384345012691519, -0.37212098566350416]),
    (0.017656226397264597, [-0.09535108920349013, -0.35128753472516716, -0.05340208195208906, 0.13068896165419672, -0.24131533056292157, 0.22808753041843607, 0.19762046756385024, -0.835621320444928]),
    (-0.05809094028714607, [-0.33899500985260167, -0.1419228302997959, -0.26707319935345636, 0.33549334468230335, -0.07000050755973088, -0.5137247815134214, 0.09352877602543848, 0.6352130046301561]),
    (-0.12233489733848273, [-0.5121118916526287, -0.162809662705327, 0.14201758832277458, 0.30919267010851403, 0.1588579639926458, 0.655888531410239, 0.3517346398316712, -0.1277593295967469]),
]

instances = []
for m_value in (2, 4, 6, 8, 10, 12):
    instances.append(
        {"name": f"m{m_value}", "axis": "m", "size": m_value, "n": 4, "m": m_value, "terms": terms_n4[:m_value]}
    )
instances.extend(
    [
        {"name": "n2", "axis": "n", "size": 2, "n": 2, "m": 4, "terms": terms_n2},
        {"name": "n6", "axis": "n", "size": 6, "n": 6, "m": 4, "terms": terms_n6},
        {"name": "n8", "axis": "n", "size": 8, "n": 8, "m": 4, "terms": terms_n8},
    ]
)

selected_instances = (
    instances if args.case == "all" else [case for case in instances if case["name"] == args.case]
)

version_model = Model()
scip_version = (
    version_model.getMajorVersion(),
    version_model.getMinorVersion(),
    version_model.getTechVersion(),
)
print(f"PySCIPOpt version          : {pyscipopt.__version__}")
print(f"SCIP version               : {'.'.join(map(str, scip_version))}")
print(f"Relative gap tolerance     : {args.relative_gap:.1e}")
print(f"Time limit per case        : {args.time_limit:.1f} seconds")

summary_rows = []

for instance in selected_instances:
    n = instance["n"]
    m = instance["m"]
    terms = instance["terms"]
    print(f"\n=== Table 5: SCIP case {instance['name']} ===")
    print(f"Dimensions                 : n={n}, m={m}")

    model = Model(f"logpop_{instance['name']}")
    model.setRealParam("limits/time", args.time_limit)
    model.setRealParam("limits/gap", args.relative_gap)
    model.setRealParam("numerics/feastol", 1.0e-9)
    model.setIntParam("randomization/randomseedshift", 0)

    x = [model.addVar(lb=0.0, ub=1.0, name=f"x_{i+1}") for i in range(n)]
    model.addCons(quicksum(x) <= 1.0, name="simplex")
    model.addCons(quicksum(x_i * x_i for x_i in x) <= 1.0, name="ball")

    log_values = []
    for j, (beta, direction) in enumerate(terms):
        affine = beta + quicksum(direction[i] * x[i] for i in range(n))
        polynomial = epsilon + affine * affine
        affine_lower = beta + min([0.0, *direction])
        affine_upper = beta + max([0.0, *direction])
        polynomial_upper = epsilon + max(affine_lower**2, affine_upper**2)

        polynomial_value = model.addVar(lb=epsilon, ub=polynomial_upper, name=f"p_{j+1}")
        model.addCons(polynomial_value == polynomial, name=f"polynomial_link_{j+1}")
        log_value = model.addVar(
            lb=math.log(epsilon),
            ub=math.log(polynomial_upper),
            name=f"log_p_{j+1}",
        )
        model.addCons(log_value <= log(polynomial_value), name=f"log_link_{j+1}")
        log_values.append(log_value)

    model.setObjective(quicksum(log_values), sense="maximize")
    solve_started = time.perf_counter()
    model.optimize()
    wall_runtime = time.perf_counter() - solve_started

    status = str(model.getStatus())
    dual_bound = model.getDualbound()
    nodes = model.getNTotalNodes()
    best_solution = model.getBestSol()

    if best_solution is None:
        feasible_value = math.nan
        absolute_gap = math.nan
        relative_gap = math.nan
        x_text = "not available"
    else:
        raw_x_value = [model.getSolVal(best_solution, x_i) for x_i in x]
        x_value = [max(0.0, value) for value in raw_x_value]
        positive_sum = sum(x_value)
        if positive_sum > 1.0:
            x_value = [value / positive_sum for value in x_value]
        x_text = "[" + ", ".join(f"{value:.8g}" for value in x_value) + "]"

        feasible_value = 0.0
        for beta, direction in terms:
            affine_value = beta + sum(direction[i] * x_value[i] for i in range(n))
            feasible_value += math.log(epsilon + affine_value * affine_value)
        absolute_gap = max(0.0, dual_bound - feasible_value)
        relative_gap = absolute_gap / max(1.0, abs(feasible_value))

    print(f"Status                    : {status}")
    print(f"Evaluated feasible value  : {feasible_value:.12g}")
    print(f"SCIP upper bound          : {dual_bound:.12g}")
    print(f"Evaluated absolute gap    : {absolute_gap:.6g}")
    print(f"Evaluated relative gap    : {relative_gap:.6g}")
    print(f"Wall-clock runtime        : {wall_runtime:.6g} seconds")
    print(f"Branch-and-bound nodes    : {nodes}")
    print(f"Feasibility-corrected x   : {x_text}")

    summary_rows.append(
        {
            "axis": instance["axis"],
            "size": instance["size"],
            "n": n,
            "m": m,
            "status": status,
            "feasible": feasible_value,
            "upper": dual_bound,
            "gap": absolute_gap,
            "relative_gap": relative_gap,
            "runtime": wall_runtime,
            "nodes": nodes,
        }
    )

print("\n=== Table 5: SCIP summary ===")
header = (
    f"{'axis':<5} {'size':>5} {'n':>3} {'m':>3} {'status':<12} "
    f"{'feasible':>13} {'upper':>13} {'abs.gap':>11} {'time':>10} {'nodes':>10}"
)
print(header)
print("-" * len(header))
for row in summary_rows:
    print(
        f"{row['axis']:<5} {row['size']:>5d} {row['n']:>3d} {row['m']:>3d} "
        f"{row['status']:<12} {row['feasible']:>13.6g} {row['upper']:>13.6g} "
        f"{row['gap']:>11.3g} {row['runtime']:>10.4g} {row['nodes']:>10d}"
    )
