"""Run the level-zero conditional SAGE calculations reported in Table 6.

This is a standalone Python entry script. It contains the fixed seed-3
instance used in the manuscript, prints all reported quantities to the
terminal, and does not read or write CSV or MAT files.
"""
# J. Choi, July 29, 2026

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys
import time
import warnings


SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR.parent / "python_packages"))

import numpy as np
import sageopt as so


# Fixed seed-3 instance generated by Table_5_6_generate_instance.m.
terms = [
    (
        0.117884086304296,
        np.array(
            [
                0.067535180041566,
                0.937395019496721,
                -0.339815902637711,
                0.0354221568232669,
            ]
        ),
    ),
    (
        -0.0177570469048091,
        np.array(
            [
                0.305399245166099,
                -0.387991744203794,
                -0.605532628516029,
                -0.624118533040113,
            ]
        ),
    ),
    (
        0.0528764705940394,
        np.array(
            [
                -0.782442773585389,
                -0.118945504714584,
                0.291090982530039,
                -0.537495407293768,
            ]
        ),
    ),
]

profiles = {
    "unit": {
        "weights": np.array([1, 1, 1], dtype=int),
        "weights_text": "[1, 1, 1]",
        "feasible_log_value": -4.07772967539828,
        "run_sage": True,
    },
    "small_integer": {
        "weights": np.array([1, 2, 3], dtype=int),
        "weights_text": "[1, 2, 3]",
        "feasible_log_value": -7.92211364420458,
        "run_sage": True,
    },
    "moderate_integer": {
        "weights": np.array([2, 5, 10], dtype=int),
        "weights_text": "[2, 5, 10]",
        "run_sage": False,
        "status": "skipped: expansion size",
        "reason": (
            "The direct product has degree 34 and can contain up to "
            "73,815 monomials."
        ),
    },
    "large_integer": {
        "weights": np.array([5, 10, 20], dtype=int),
        "weights_text": "[5, 10, 20]",
        "run_sage": False,
        "status": "skipped: expansion size",
        "reason": (
            "The direct product has degree 70 and can contain up to "
            "1,150,626 monomials."
        ),
    },
    "fractional": {
        "weights": np.array([0.5, 1.5, 2.5]),
        "weights_text": "[0.5, 1.5, 2.5]",
        "run_sage": False,
        "status": "not applicable",
        "reason": (
            "Noninteger powers do not give a finite signomial expansion "
            "in the formulation used here."
        ),
    },
    "irrational": {
        "weights": np.array([math.sqrt(2), math.pi / 2, math.e / 2]),
        "weights_text": "[sqrt(2), pi/2, e/2]",
        "run_sage": False,
        "status": "not applicable",
        "reason": (
            "Irrational powers do not give a finite signomial expansion "
            "in the formulation used here."
        ),
    },
}

parser = argparse.ArgumentParser()
parser.add_argument(
    "--profile",
    choices=(*profiles.keys(), "all"),
    default="all",
    help=(
        "Profile to examine. By default, all six manuscript profiles are "
        "listed and every applicable SAGE calculation is run."
    ),
)
args = parser.parse_args()

selected_profiles = (
    tuple(profiles) if args.profile == "all" else (args.profile,)
)

summary_rows = []

for profile_name in selected_profiles:
    profile = profiles[profile_name]
    weights = profile["weights"]
    weights_text = profile["weights_text"]

    if not profile["run_sage"]:
        print(f"\n=== Table 6: SAGE profile {profile_name} ===")
        print(f"Coefficient vector a      : {weights_text}")
        print(f"Status                    : {profile['status']}")
        print(f"Reason                    : {profile['reason']}")
        summary_rows.append(
            {
                "profile": profile_name,
                "weights": weights_text,
                "status": profile["status"],
                "bound": math.nan,
                "gap": math.nan,
                "time": math.nan,
            }
        )
        continue

    feasible_log_value = profile["feasible_log_value"]

    z = so.standard_sig_monomials(4)
    polynomials = []
    for beta, direction in terms:
        affine = beta + sum(direction[i] * z[i] for i in range(4))
        polynomials.append(0.05 + affine**2)

    objective = 1
    for polynomial, weight in zip(polynomials, weights):
        objective *= polynomial ** int(weight)

    negative_objective = -objective
    simplex = 1 - sum(z)
    domain = so.infer_domain(negative_objective, [simplex], [])
    if domain is None:
        raise RuntimeError("Sageopt could not infer the log-simplex domain.")

    started = time.perf_counter()
    problem = so.sig_relaxation(
        negative_objective, X=domain, form="dual", ell=0
    )
    construction_time = time.perf_counter() - started

    started = time.perf_counter()
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore", message="Argument .* Incorrect array format.*"
        )
        solve_result = problem.solve(solver="MOSEK", verbose=True)
    solve_time = time.perf_counter() - started

    product_upper_bound = -float(problem.value)
    log_upper_bound = (
        math.log(product_upper_bound)
        if product_upper_bound > 0
        else math.nan
    )
    sage_gap = log_upper_bound - feasible_log_value
    total_time = construction_time + solve_time

    print(f"\n=== Table 6: SAGE profile {profile_name} ===")
    print(f"Coefficient vector a      : {weights.tolist()}")
    print("SAGE hierarchy level ell  : 0")
    print(f"Solver status             : {problem.status}")
    print(f"Solve-result status       : {solve_result[0]}")
    print(f"SAGE log upper bound      : {log_upper_bound:.10f}")
    print(f"Feasible log value        : {feasible_log_value:.10f}")
    print(f"Delta_SAGE                : {sage_gap:.10f}")
    print(f"Construction time (seconds): {construction_time:.4f}")
    print(f"Solver time (seconds)      : {solve_time:.4f}")
    print(f"Total runtime (seconds)    : {total_time:.4f}")

    summary_rows.append(
        {
            "profile": profile_name,
            "weights": weights_text,
            "status": str(problem.status),
            "bound": log_upper_bound,
            "gap": sage_gap,
            "time": total_time,
        }
    )


def format_number(value):
    """Format a reported number or show a dash when no solve was performed."""
    return "-" if math.isnan(value) else f"{value:.6f}"


print("\n=== Table 6: SAGE summary ===")
print(
    f"{'profile':<18} {'coefficient vector a':<24} "
    f"{'status':<25} {'log bound':>12} {'gap':>12} {'total sec.':>12}"
)
print("-" * 108)
for row in summary_rows:
    print(
        f"{row['profile']:<18} {row['weights']:<24} "
        f"{row['status']:<25} {format_number(row['bound']):>12} "
        f"{format_number(row['gap']):>12} "
        f"{format_number(row['time']):>12}"
    )
