"""Run SCIP on the fixed log-polynomial instance reported in Table 6.

The script solves the original log-polynomial problem directly. It prints
SCIP's best feasible value, certified upper bound, optimality gap, node
count, and solver runtime for each coefficient profile. No result files
are created.
"""
# J. Choi, August 4, 2026

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys
import time


SCRIPT_DIR = Path(__file__).resolve().parent
PACKAGE_DIR = SCRIPT_DIR.parent / "python_packages"
sys.path.insert(0, str(PACKAGE_DIR))

import pyscipopt
from pyscipopt import Model, log, quicksum


parser = argparse.ArgumentParser()
parser.add_argument(
    "--profile",
    choices=(
        "unit",
        "small_integer",
        "moderate_integer",
        "large_integer",
        "fractional",
        "irrational",
        "all",
    ),
    default="all",
    help="Coefficient profile to solve. The default solves all six profiles.",
)
parser.add_argument(
    "--time-limit",
    type=float,
    default=600.0,
    help="SCIP time limit in seconds for each profile (default: 600).",
)
parser.add_argument(
    "--relative-gap",
    type=float,
    default=1.0e-6,
    help="Relative optimality-gap tolerance (default: 1e-6).",
)
args = parser.parse_args()

if args.time_limit <= 0:
    parser.error("--time-limit must be positive")
if args.relative_gap < 0:
    parser.error("--relative-gap must be nonnegative")


# Fixed seed-3 instance generated by Table_5_6_generate_instance.m.
epsilon = 0.05
terms = [
    (
        0.117884086304296,
        [
            0.067535180041566,
            0.937395019496721,
            -0.339815902637711,
            0.0354221568232669,
        ],
    ),
    (
        -0.0177570469048091,
        [
            0.305399245166099,
            -0.387991744203794,
            -0.605532628516029,
            -0.624118533040113,
        ],
    ),
    (
        0.0528764705940394,
        [
            -0.782442773585389,
            -0.118945504714584,
            0.291090982530039,
            -0.537495407293768,
        ],
    ),
]

profiles = {
    "unit": [1.0, 1.0, 1.0],
    "small_integer": [1.0, 2.0, 3.0],
    "moderate_integer": [2.0, 5.0, 10.0],
    "large_integer": [5.0, 10.0, 20.0],
    "fractional": [0.5, 1.5, 2.5],
    "irrational": [math.sqrt(2.0), math.pi / 2.0, math.e / 2.0],
}

selected_profiles = (
    tuple(profiles) if args.profile == "all" else (args.profile,)
)

version_model = Model()
scip_version = (
    version_model.getMajorVersion(),
    version_model.getMinorVersion(),
    version_model.getTechVersion(),
)
print(f"PySCIPOpt version          : {pyscipopt.__version__}")
print(f"SCIP version               : {'.'.join(map(str, scip_version))}")
print(f"Relative gap tolerance     : {args.relative_gap:.1e}")
print(f"Time limit per profile     : {args.time_limit:.1f} seconds")

summary_rows = []

for profile_name in selected_profiles:
    weights = profiles[profile_name]
    print(f"\n=== Table 6: SCIP profile {profile_name} ===")
    print("Coefficient vector a      : " + ", ".join(f"{a:.10g}" for a in weights))

    model = Model(f"logpop_{profile_name}")
    model.setRealParam("limits/time", args.time_limit)
    model.setRealParam("limits/gap", args.relative_gap)
    model.setRealParam("numerics/feastol", 1.0e-9)
    model.setIntParam("randomization/randomseedshift", 0)

    x = [model.addVar(lb=0.0, ub=1.0, name=f"x_{i+1}") for i in range(4)]
    model.addCons(quicksum(x) <= 1.0, name="simplex")
    model.addCons(quicksum(x_i * x_i for x_i in x) <= 1.0, name="ball")

    log_values = []
    for j, (beta, direction) in enumerate(terms):
        affine = beta + quicksum(direction[i] * x[i] for i in range(4))
        polynomial = epsilon + affine * affine

        affine_lower = beta + min([0.0, *direction])
        affine_upper = beta + max([0.0, *direction])
        polynomial_upper = epsilon + max(affine_lower**2, affine_upper**2)

        polynomial_value = model.addVar(
            lb=epsilon,
            ub=polynomial_upper,
            name=f"p_{j+1}",
        )
        model.addCons(
            polynomial_value == polynomial,
            name=f"polynomial_link_{j+1}",
        )

        log_value = model.addVar(
            lb=math.log(epsilon),
            ub=math.log(polynomial_upper),
            name=f"log_p_{j+1}",
        )
        model.addCons(
            log_value <= log(polynomial_value),
            name=f"log_link_{j+1}",
        )
        log_values.append(log_value)

    model.setObjective(
        quicksum(weights[j] * log_values[j] for j in range(3)),
        sense="maximize",
    )
    solve_started = time.perf_counter()
    model.optimize()
    wall_runtime = time.perf_counter() - solve_started

    status = str(model.getStatus())
    solver_time = model.getSolvingTime()
    nodes = model.getNTotalNodes()
    scip_primal_bound = model.getPrimalbound()
    dual_bound = model.getDualbound()
    scip_relative_gap = model.getGap()

    best_solution = model.getBestSol()
    if best_solution is None:
        x_text = "not available"
        feasible_value = math.nan
        absolute_gap = math.nan
        relative_gap = math.nan
    else:
        raw_x_value = [model.getSolVal(best_solution, x_i) for x_i in x]
        x_value = [max(0.0, value) for value in raw_x_value]
        positive_sum = sum(x_value)
        if positive_sum > 1.0:
            x_value = [value / positive_sum for value in x_value]
        x_text = "[" + ", ".join(f"{value:.10g}" for value in x_value) + "]"
        feasible_value = 0.0
        for weight, (beta, direction) in zip(weights, terms):
            affine_value = beta + sum(
                direction[i] * x_value[i] for i in range(4)
            )
            feasible_value += weight * math.log(
                epsilon + affine_value * affine_value
            )
        absolute_gap = max(0.0, dual_bound - feasible_value)
        relative_gap = absolute_gap / max(1.0, abs(feasible_value))

    print(f"Status                    : {status}")
    print(f"SCIP primal bound         : {scip_primal_bound:.12g}")
    print(f"Evaluated feasible value  : {feasible_value:.12g}")
    print(f"SCIP upper bound          : {dual_bound:.12g}")
    print(f"Evaluated absolute gap    : {absolute_gap:.6g}")
    print(f"Evaluated relative gap    : {relative_gap:.6g}")
    print(f"SCIP reported gap         : {scip_relative_gap:.6g}")
    print(f"SCIP solver time          : {solver_time:.6g} seconds")
    print(f"Wall-clock runtime        : {wall_runtime:.6g} seconds")
    print(f"Branch-and-bound nodes    : {nodes}")
    print(f"Feasibility-corrected x   : {x_text}")

    summary_rows.append(
        {
            "profile": profile_name,
            "weights": "[" + ", ".join(f"{a:.6g}" for a in weights) + "]",
            "status": status,
            "primal": feasible_value,
            "dual": dual_bound,
            "absolute_gap": absolute_gap,
            "relative_gap": relative_gap,
            "runtime": wall_runtime,
            "nodes": nodes,
        }
    )

print("\n=== Table 6: SCIP summary ===")
header = (
    f"{'profile':<18} {'a':<30} {'status':<12} "
    f"{'primal':>13} {'upper':>13} {'rel.gap':>11} {'time':>10} {'nodes':>10}"
)
print(header)
print("-" * len(header))
for row in summary_rows:
    print(
        f"{row['profile']:<18} {row['weights']:<30} {row['status']:<12} "
        f"{row['primal']:>13.6g} {row['dual']:>13.6g} "
        f"{row['relative_gap']:>11.3g} {row['runtime']:>10.4g} "
        f"{row['nodes']:>10d}"
    )
